image: europeanxfel/karabo-ci:miniconda-3

before_script:
    - export http_proxy="http://exflwgs06.desy.de:3128/"
    - export https_proxy="http://exflwgs06.desy.de:3128/"
    - apt update
    - apt -y install libopenmpi-dev
    - pip install .[test]

stages:
    - unittest

unittest:
    stage: unittest
    script:
        - python setup.py test